sudo: required
language: generic

services:
  # Install docker-cli
  - docker

before_install:
  - docker build -t mzagol/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mzagol/docker-react npm run test
